version: '3.3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
  
  wordpress:
    depends_on:
      - mysql
    image: shul-wordpress:latest
    environment:
      - MYSQL_HOST=mysql
    links:
      - mysql
    ports:
      - "8000:80"
